//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace shtik.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("shtik.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] fira_sans_v7_latin_700_woff {
            get {
                object obj = ResourceManager.GetObject("fira_sans_v7_latin_700_woff", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] fira_sans_v7_latin_700_woff2 {
            get {
                object obj = ResourceManager.GetObject("fira_sans_v7_latin_700_woff2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] fira_sans_v7_latin_700italic_woff {
            get {
                object obj = ResourceManager.GetObject("fira_sans_v7_latin_700italic_woff", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] fira_sans_v7_latin_700italic_woff2 {
            get {
                object obj = ResourceManager.GetObject("fira_sans_v7_latin_700italic_woff2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] lato_v13_latin_italic_woff {
            get {
                object obj = ResourceManager.GetObject("lato_v13_latin_italic_woff", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] lato_v13_latin_italic_woff2 {
            get {
                object obj = ResourceManager.GetObject("lato_v13_latin_italic_woff2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] lato_v13_latin_regular_woff {
            get {
                object obj = ResourceManager.GetObject("lato_v13_latin_regular_woff", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] lato_v13_latin_regular_woff2 {
            get {
                object obj = ResourceManager.GetObject("lato_v13_latin_regular_woff2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*! normalize.css v7.0.0 | MIT License | github.com/necolas/normalize.css */button,hr,input{overflow:visible}audio,canvas,progress,video{display:inline-block}progress,sub,sup{vertical-align:baseline}[type=checkbox],[type=radio],legend{box-sizing:border-box;padding:0}html{line-height:1.15;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%}body{margin:0}article,aside,details,figcaption,figure,footer,header,main,menu,nav,section{display:block}h1{font-size:2em;margin:.67em 0}figure{margin:1em 40px}hr{box-s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string normalize_css {
            get {
                return ResourceManager.GetString("normalize_css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to var page = 0;
        ///
        ///const Keys = {
        ///    LeftArrow: 37,
        ///    RightArrow: 39,
        ///    Space: 32
        ///};
        ///
        ///function loadPage(url) {
        ///    return fetch(url, { method: &quot;GET&quot; }).then(response =&gt; response.text());
        ///}
        ///
        ///function transition() {
        ///    const url = window.location.href;
        ///    const newPage = parseInt(url.replace(/.*\//, &quot;&quot;));
        ///    loadPage(url).then(html =&gt; {
        ///        const newDocument = document.createElement(&quot;html&quot;);
        ///        newDocument.innerHTML = html;
        ///
        ///        document.querySelector(&quot;title&quot;).innerText = n [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string script_js {
            get {
                return ResourceManager.GetString("script_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to var Shtik;
        ///(function (Shtik) {
        ///    var currentPage = 0;
        ///    var Keys = {
        ///        LeftArrow: 37,
        ///        RightArrow: 39,
        ///        Space: 32
        ///    };
        ///    function loadPage(url) {
        ///        return fetch(url, { method: &quot;GET&quot; }).then(function (response) { return response.text(); });
        ///    }
        ///    function transition() {
        ///        var url = window.location.href;
        ///        loadPage(url).then(function (html) {
        ///            var newDocument = document.createElement(&quot;html&quot;);
        ///            newDocument.innerHTML = html;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string shtik_js {
            get {
                return ResourceManager.GetString("shtik_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;{{title}}&lt;/title&gt;
        ///    &lt;!-- ReSharper disable once Html.PathError --&gt;
        ///    &lt;link href=&quot;normalize.css&quot; rel=&quot;stylesheet&quot; /&gt;
        ///    &lt;link href=&quot;theme.css&quot; rel=&quot;stylesheet&quot; /&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///&lt;main&gt;
        ///&lt;article class=&quot;{{layout}}&quot;&gt;
        ///    {{content}}
        ///&lt;/article&gt;
        ///&lt;nav&gt;
        ///    &lt;a id=&quot;previous-link&quot; href=&quot;{{previousIndex}}&quot;&gt;&amp;lt;&lt;/a&gt;
        ///    &lt;a id=&quot;next-link&quot; href=&quot;{{nextIndex}}&quot;&gt;&amp;gt;&lt;/a&gt;
        ///&lt;/nav&gt;
        ///&lt;/main&gt;
        ///&lt;!-- ReSharper disable once Html.PathError -- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string template_html {
            get {
                return ResourceManager.GetString("template_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /* fira-sans-700 - latin */
        ///@font-face { font-family: &apos;Fira Sans&apos;; font-style: normal; font-weight: 700; src: local(&apos;Fira Sans Bold&apos;), local(&apos;FiraSans-Bold&apos;), url(&apos;fonts/fira-sans-v7-latin-700.woff2&apos;) format(&apos;woff2&apos;), url(&apos;fonts/fira-sans-v7-latin-700.woff&apos;) format(&apos;woff&apos;); /* IE 9+ */ }
        ////* fira-sans-700italic - latin */
        ///@font-face { font-family: &apos;Fira Sans&apos;; font-style: italic; font-weight: 700; src: local(&apos;Fira Sans Bold Italic&apos;), local(&apos;FiraSans-BoldItalic&apos;), url(&apos;fonts/fira-sans-v7-latin-700italic.wo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string theme_css {
            get {
                return ResourceManager.GetString("theme_css", resourceCulture);
            }
        }
    }
}
